export type CommandFamily = 'player' | 'business' | 'property' | 'economy' | 'market' | 'crypto' | 'jobs' | 'quests' | 'exploration' | 'events' | 'clan' | 'mafia' | 'hitman' | 'crime' | 'prison' | 'gambling' | 'war' | 'leaderboard' | 'support' | 'moderation' | 'admin';

export type CommandEntry = {
  command: string;
  aliases: string[];
  family: CommandFamily;
  description: string;
  requiresRole?: 'Businessman' | 'Mafia' | 'Hitman';
  persistent?: boolean;
};

export const COMMAND_MATRIX: CommandEntry[] = [
  { command: 'start', aliases: ['start'], family: 'player', description: 'Initialize a player session.' },
  { command: 'menu', aliases: ['menu'], family: 'player', description: 'Open the role-based command terminal.' },
  { command: 'help', aliases: ['help'], family: 'player', description: 'View command help.' },
  { command: 'guide', aliases: ['guide'], family: 'player', description: 'View the main game guide.' },
  { command: 'profile', aliases: ['profile', 'whoami'], family: 'player', description: 'View the current player profile.' },
  { command: 'status', aliases: ['status', 'account'], family: 'player', description: 'Show account and status overview.' },
  { command: 'stats', aliases: ['stats'], family: 'player', description: 'View player stats.' },
  { command: 'balance', aliases: ['balance'], family: 'economy', description: 'View cash and bank balances.' },
  { command: 'inventory', aliases: ['inventory', 'inv'], family: 'player', description: 'View inventory and equipped items.' },
  { command: 'rank', aliases: ['rank', 'leaderboard', 'lb'], family: 'leaderboard', description: 'Show leaderboard rank.' },
  { command: 'titles', aliases: ['titles'], family: 'player', description: 'View unlocked titles.' },
  { command: 'achievements', aliases: ['achievements'], family: 'player', description: 'View achievement progress.' },
  { command: 'history', aliases: ['history', 'finance'], family: 'economy', description: 'View transaction and financial history.' },
  { command: 'compare', aliases: ['compare'], family: 'player', description: 'Compare player performance.' },
  { command: 'biz', aliases: ['biz', 'business'], family: 'business', description: 'Access business command console.' },
  { command: 'biz list', aliases: ['biz list', 'business list'], family: 'business', description: 'List available businesses.' },
  { command: 'biz buy', aliases: ['biz buy'], family: 'business', description: 'Buy a business.' },
  { command: 'biz info', aliases: ['biz info'], family: 'business', description: 'Show details for a business.' },
  { command: 'biz upgrade', aliases: ['biz upgrade'], family: 'business', description: 'Upgrade a business.' },
  { command: 'biz sell', aliases: ['biz sell'], family: 'business', description: 'Sell a business.' },
  { command: 'collect', aliases: ['collect', 'income'], family: 'business', description: 'Collect business income.' },
  { command: 'production', aliases: ['production', 'profit'], family: 'business', description: 'Check production and margin.' },
  { command: 'expenses', aliases: ['expenses'], family: 'business', description: 'Review maintenance and cost profile.' },
  { command: 'property', aliases: ['property', 'prop'], family: 'property', description: 'Access property systems.' },
  { command: 'prop list', aliases: ['prop list'], family: 'property', description: 'List properties for sale.' },
  { command: 'prop buy', aliases: ['prop buy'], family: 'property', description: 'Buy a property.' },
  { command: 'prop info', aliases: ['prop info'], family: 'property', description: 'Inspect property.' },
  { command: 'prop upgrade', aliases: ['prop upgrade'], family: 'property', description: 'Upgrade property.' },
  { command: 'vehicle', aliases: ['vehicle', 'vehicles'], family: 'property', description: 'Access vehicle garage.' },
  { command: 'vehicle buy', aliases: ['vehicle buy'], family: 'property', description: 'Purchase a vehicle.' },
  { command: 'vehicle info', aliases: ['vehicle info'], family: 'property', description: 'Inspect vehicle.' },
  { command: 'bank', aliases: ['bank', 'deposit', 'withdraw'], family: 'economy', description: 'Manage bank account.' },
  { command: 'loan', aliases: ['loan', 'borrow'], family: 'economy', description: 'Take a loan or review loan terms.' },
  { command: 'loan status', aliases: ['loan status'], family: 'economy', description: 'Check debt obligations.' },
  { command: 'loan repay', aliases: ['loan repay'], family: 'economy', description: 'Repay debt.' },
  { command: 'debt', aliases: ['debt', 'credit'], family: 'economy', description: 'Review debt and credit details.' },
  { command: 'liquidate', aliases: ['liquidate'], family: 'economy', description: 'Liquidate assets.' },
  { command: 'assets', aliases: ['assets', 'networth'], family: 'economy', description: 'Evaluate total holdings.' },
  { command: 'invest', aliases: ['invest', 'investments'], family: 'economy', description: 'Invest or review investments.' },
  { command: 'market', aliases: ['market'], family: 'market', description: 'Access market trading console.' },
  { command: 'market list', aliases: ['market list'], family: 'market', description: 'List market items.' },
  { command: 'market buy', aliases: ['market buy'], family: 'market', description: 'Buy a market item.' },
  { command: 'market sell', aliases: ['market sell'], family: 'market', description: 'Sell a market item.' },
  { command: 'market search', aliases: ['market search'], family: 'market', description: 'Search for market items.' },
  { command: 'trade', aliases: ['trade'], family: 'market', description: 'Trade items or funds.' },
  { command: 'auction', aliases: ['auction'], family: 'market', description: 'Access auction house.' },
  { command: 'auction bid', aliases: ['auction bid'], family: 'market', description: 'Bid on an auction item.' },
  { command: 'crypto', aliases: ['crypto'], family: 'crypto', description: 'Access crypto market.' },
  { command: 'crypto market', aliases: ['crypto market', 'crypto list'], family: 'crypto', description: 'List crypto market data.' },
  { command: 'crypto price', aliases: ['crypto price'], family: 'crypto', description: 'View token prices.' },
  { command: 'crypto buy', aliases: ['crypto buy'], family: 'crypto', description: 'Buy crypto asset.' },
  { command: 'crypto sell', aliases: ['crypto sell'], family: 'crypto', description: 'Sell crypto asset.' },
  { command: 'crypto portfolio', aliases: ['crypto portfolio'], family: 'crypto', description: 'View crypto portfolio.' },
  { command: 'jobs', aliases: ['jobs', 'job'], family: 'jobs', description: 'List available jobs.' },
  { command: 'job work', aliases: ['job work'], family: 'jobs', description: 'Work a job for payout.' },
  { command: 'quests', aliases: ['quests', 'quest'], family: 'quests', description: 'View quests and claim rewards.' },
  { command: 'quest claim', aliases: ['quest claim'], family: 'quests', description: 'Claim a quest reward.' },
  { command: 'explore', aliases: ['explore'], family: 'exploration', description: 'Explore the city districts.' },
  { command: 'events', aliases: ['events', 'event'], family: 'events', description: 'Check current in-game events.' },
  { command: 'clan', aliases: ['clan'], family: 'clan', description: 'Open clan console.' },
  { command: 'clan create', aliases: ['clan create'], family: 'clan', description: 'Create a clan.' },
  { command: 'clan join', aliases: ['clan join'], family: 'clan', description: 'Join a clan.' },
  { command: 'clan info', aliases: ['clan info'], family: 'clan', description: 'View clan info.' },
  { command: 'clan members', aliases: ['clan members'], family: 'clan', description: 'View clan members.' },
  { command: 'clan deposit', aliases: ['clan deposit'], family: 'clan', description: 'Deposit treasury funds.' },
  { command: 'clan withdraw', aliases: ['clan withdraw'], family: 'clan', description: 'Withdraw treasury funds.' },
  { command: 'combat', aliases: ['combat', 'train'], family: 'mafia', description: 'Train and increase combat readiness.' },
  { command: 'rob', aliases: ['rob'], family: 'crime', description: 'Attempt a robbery.' },
  { command: 'raid', aliases: ['raid'], family: 'crime', description: 'Raid an enemy target.' },
  { command: 'heist', aliases: ['heist', 'sh', 'jh', 'gmh', 'dh', 'bh'], family: 'crime', description: 'Attempt a heist.' },
  { command: 'wanted', aliases: ['wanted', 'heat'], family: 'crime', description: 'View wanted level and heat.' },
  { command: 'hit', aliases: ['hit'], family: 'hitman', description: 'Open hitman operation menu.' },
  { command: 'contracts', aliases: ['contracts', 'contract'], family: 'hitman', description: 'Review available contracts.' },
  { command: 'bounty', aliases: ['bounty'], family: 'hitman', description: 'Track bounty information.' },
  { command: 'blackjack', aliases: ['blackjack', 'bj'], family: 'gambling', description: 'Open the blackjack table.' },
  { command: 'bj hit', aliases: ['bj hit'], family: 'gambling', description: 'Draw a blackjack card.' },
  { command: 'bj stand', aliases: ['bj stand'], family: 'gambling', description: 'Stand on the current blackjack hand.' },
  { command: 'bj double', aliases: ['bj double'], family: 'gambling', description: 'Double down on blackjack.' },
  { command: 'gamble', aliases: ['gamble', 'slots', 'dice', 'coinflip', 'highlow'], family: 'gambling', description: 'Play casino games.' },
  { command: 'lotto', aliases: ['lotto'], family: 'gambling', description: 'Enter the global lotto.' },
  { command: 'war', aliases: ['war', 'warground'], family: 'war', description: 'Open wartime interface.' },
  { command: 'war info', aliases: ['war info'], family: 'war', description: 'View ongoing war status.' },
  { command: 'war status', aliases: ['war status'], family: 'war', description: 'Read current war scoreboard.' },
  { command: 'territory', aliases: ['territory'], family: 'war', description: 'Review territorial control.' },
  { command: 'leaderboard', aliases: ['leaderboard', 'rankings', 'richlist', 'clanrank', 'warrank', 'top'], family: 'leaderboard', description: 'View live leaderboards.' },
  { command: 'ping', aliases: ['ping'], family: 'support', description: 'Check bot responsiveness.' },
  { command: 'uptime', aliases: ['uptime', 'botinfo', 'version'], family: 'support', description: 'View bot uptime and status.' },
  { command: 'news', aliases: ['news', 'quote'], family: 'support', description: 'Read world news and quotes.' },
  { command: 'rules', aliases: ['rules', 'support', 'feedback', 'report'], family: 'support', description: 'Review rules and support channels.' },
  { command: 'moderation', aliases: ['moderation'], family: 'moderation', description: 'Open the moderation console.' },
  { command: 'kick', aliases: ['kick'], family: 'moderation', description: 'Moderate a group member.' },
  { command: 'ban', aliases: ['ban', 'mute', 'unmute', 'warn', 'warns'], family: 'moderation', description: 'Moderate a player.' },
  { command: 'admin', aliases: ['admin'], family: 'admin', description: 'Admin panel access.' },
  { command: 'admin panel', aliases: ['admin panel'], family: 'admin', description: 'Open admin panel.' },
  { command: 'admin users', aliases: ['admin users'], family: 'admin', description: 'Review user list.' },
  { command: 'admin give', aliases: ['admin give'], family: 'admin', description: 'Grant resources to a player.' }
];

export const MENU_GROUPS: Record<string, string[]> = {
  Businessman: [
    '� CHARACTER',
    '.start .profile .status .stats .inventory',
    '💼 EMPIRE',
    '.biz .biz list .biz buy .collect .production .expenses',
    '🏦 FINANCE',
    '.balance .bank .loan .debt .assets .invest',
    '🏠 PROPERTY',
    '.property .prop list .prop buy .vehicle .vehicle list',
    '🪙 CRYPTO',
    '.crypto .crypto market .crypto price .crypto portfolio',
    '🏴 CLAN',
    '.clan .clan create .clan info .clan members',
    '🚨 OPERATIONS',
    '.rob .raid .heist .wanted .combat',
    '🎰 GAMBLING',
    '.blackjack .lotto .gamble',
    '🏆 RANKINGS',
    '.leaderboard .rank',
    '⚔️ WAR',
    '.war .war info .territory'
  ],
  Mafia: [
    '👤 CHARACTER',
    '.start .profile .status .stats .inventory',
    '🕴️ MAFIA',
    '.combat .rob .raid .heist .wanted',
    '🏴 CLAN',
    '.clan .clan create .clan info .clan members',
    '💰 ECONOMY',
    '.balance .bank .loan .invest .assets',
    '🏠 PROPERTY',
    '.property .prop list .prop buy .vehicle .vehicle list',
    '⚔️ WAR',
    '.war .war info .territory',
    '🎰 GAMBLING',
    '.blackjack .lotto',
    '🏆 RANKINGS',
    '.leaderboard .rank'
  ],
  Hitman: [
    '👤 CHARACTER',
    '.start .profile .status .stats .inventory',
    '🎯 HITMAN',
    '.hit .contracts .bounty .rob .heist',
    '💰 ECONOMY',
    '.balance .bank .loan .invest .assets',
    '🪙 CRYPTO',
    '.crypto .crypto market .crypto price .crypto portfolio',
    '🏴 CLAN',
    '.clan .clan create .clan info .clan members',
    '🏆 RANKINGS',
    '.leaderboard .rank',
    '⚔️ WAR',
    '.war .war info .territory'
  ]
};

export const GUIDE_TOPICS = [
  'business', 'economy', 'loans', 'crypto', 'property', 'vehicles', 'jobs', 'quests', 'clan',
  'mafia', 'hitman', 'crime', 'heist', 'raid', 'prison', 'gambling', 'blackjack', 'lotto', 'war',
  'leaderboard', 'moderation', 'commands'
];
